### ISSUE TITLE
show all cards that have been played

### ISSUE THREAD

**Issue by MustafaHaddara** [MustafaHaddara/the-mind#2]
change the drop zone in the middle so it shows all of the cards that have been played, not just the last one. 

we still want the most recent card that was played to be different in some way-- perhaps it's bigger? highlighted?

**Comment by rezziemaven** [comment]
Hey @MustafaHaddara! I'd love to take this one on, and perhaps #5 as well while I'm at it (if necessary). Can you assign me to this issue?

**Comment by MustafaHaddara** [comment]
Go for it!

**Comment by rezziemaven** [comment]
Hi @MustafaHaddara! I decided to stick to the scope of this issue and just display all of the cards played, so issue #5 is still up for grabs! I don't mind taking it up though, so I'll ask you to assign this to me.

Just made a PR (#10) to address this issue.

**Comment by MustafaHaddara** [comment]
closed in https://github.com/MustafaHaddara/the-mind/pull/10
