### ISSUE TITLE
dropped cards should stay where they are

### ISSUE THREAD

**Issue by MustafaHaddara** [MustafaHaddara/the-mind#5]
when dropping a card, it should remain where the person dropped it, instead of getting "absorbed" into the drop zone. 

this may conflict with #2; discuss.

**Comment by rezziemaven** [comment]
Hey @MustafaHaddara! I'd love to take this one on! Would you assign it to me?

**Comment by MustafaHaddara** [comment]
go for it!

**Comment by rezziemaven** [comment]
Hi @MustafaHaddara! Just submitted a PR for this (see #15). Check it out when you can!

**Comment by MustafaHaddara** [comment]
completed in #15
