### ISSUE TITLE
rewrite turn functions to be pure 

### ISSUE THREAD

**Issue by MustafaHaddara** [MustafaHaddara/the-mind#6]
right now the four turn functions in `Game.js` (`playCard`, `aboutToPlay`, `cancelPlay`, and `resetGame`) all mutate the game state `G`. 

Rewrite them to treat `G` as immutable.

**Comment by rezziemaven** [comment]
Hey @MustafaHaddara! I can take a stab at this if you don't mind assigning me!

**Comment by MustafaHaddara** [comment]
sure thing!
