### ISSUE TITLE
unit tests

### ISSUE THREAD

**Issue by MustafaHaddara** [MustafaHaddara/the-mind#7]
most of the functions in `Game.js` are immutable/pure/easy to test. data goes in -> data comes out. 

add unit tests for

helpers:
- `isLosingMove`
- `isWinningMove`
- `isGameOver`

turns:
- `playCard`
- `aboutToPlay`
- `cancelPlay`
- `resetGame`

Tests for the turns _probably_ depend on #6. 

for bonus points, add tests for `shuffleDeck` and `setupGame`. These will likely require mock functions that "shuffle" the deck deterministically so that we can have reliable expected output.

**Comment by JStruk** [comment]
I can pick up this issue if you don't mind assigning me 😄

**Comment by MustafaHaddara** [comment]
Go for it!

**Comment by JStruk** [comment]
Hi @MustafaHaddara are you able to take a look at/merge the PR at https://github.com/MustafaHaddara/the-mind/pull/9 ?
Thanks 😄

**Comment by MustafaHaddara** [comment]
closed in https://github.com/MustafaHaddara/the-mind/pull/9
